// <auto-generated />
using System;
using Library.API.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Library.API.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20200605083712_SeedDataByZyl2")]
    partial class SeedDataByZyl2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Library.API.Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("BirthDate");

                    b.Property<string>("BirthPlace")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new { Id = new Guid("72d5b5f5-3008-49b7-b0d6-cc337f1a3330"), BirthDate = new DateTimeOffset(new DateTime(1960, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)), BirthPlace = "Place 1", Email = "author1@xxx.com", Name = "Author 1" },
                        new { Id = new Guid("7d04a48e-be4e-468e-8ce2-3ac0a0c79549"), BirthDate = new DateTimeOffset(new DateTime(1968, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)), BirthPlace = "Place 2", Email = "author2@xxx.com", Name = "Author 2" }
                    );
                });

            modelBuilder.Entity("Library.API.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AuthorId");

                    b.Property<string>("Description")
                        .HasMaxLength(500);

                    b.Property<int>("Pages");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new { Id = new Guid("7d8ebda9-2634-4c0f-9469-0695d6132153"), AuthorId = new Guid("72d5b5f5-3008-49b7-b0d6-cc337f1a3330"), Description = "Description of Book 1", Pages = 281, Title = "Book 1" },
                        new { Id = new Guid("1ed47697-aa7d-48c2-aa39-305d0e13b3aa"), AuthorId = new Guid("72d5b5f5-3008-49b7-b0d6-cc337f1a3330"), Description = "Description of Book 2", Pages = 370, Title = "Book 2" },
                        new { Id = new Guid("5f82c852-375d-4926-a3b7-84b63fc1bfae"), AuthorId = new Guid("7d04a48e-be4e-468e-8ce2-3ac0a0c79549"), Description = "Description of Book 3", Pages = 229, Title = "Book 3" },
                        new { Id = new Guid("418a5b20-460b-4604-be17-2b0809e19acd"), AuthorId = new Guid("7d04a48e-be4e-468e-8ce2-3ac0a0c79549"), Description = "Description of Book 4", Pages = 440, Title = "Book 4" }
                    );
                });

            modelBuilder.Entity("Library.API.Entities.Book", b =>
                {
                    b.HasOne("Library.API.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
